# Generated by Django 2.2.9 on 2020-02-04 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacte', '0002_auto_20200130_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numero de telephone doit contenir 10 chiffres', regex='^\\d{9,10}$')]),
        ),
    ]
