# Generated by Django 2.2.9 on 2020-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200130_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('0', 'Annonce'), ('1', 'Administratif'), ('2', 'Agenda'), ('3', 'Mesure du Pacte'), ('4', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
