# Generated by Django 2.2.9 on 2020-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200206_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('0', 'Annonce'), ('1', 'Administratif'), ('2', 'Evenement'), ('3', 'Mesure du Pacte'), ('3', 'Echanges avec les candidats'), ('4', 'Reunion publique'), ('5', 'Covoiturage'), ('5', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
