# Generated by Django 2.2.9 on 2020-02-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name="Titre de l'événement (si laissé vide, ce sera le titre de l'article)"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='article',
            field=models.ForeignKey(help_text="L'événement doit être associé à un article existant (sinon créez un article avec une date)", on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
