# Generated by Django 2.2.9 on 2020-03-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200305_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('0', 'Annonce'), ('1', 'Administratif'), ('2', 'Mesure / action'), ('3', 'Echanges avec les candidats'), ('4', 'Réunion'), ('5', 'Idée'), ('6', 'Listes signataires'), ('7', 'Divers')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
