# Generated by Django 2.2.13 on 2020-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200305_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='territoire',
            field=models.CharField(choices=[('0', 'Argelès-sur-Mer,'), ('1', 'Bages'), ('2', 'Banyuls-sur-Mer'), ('3', 'Cerbère'), ('4', 'Collioure'), ('5', 'Elne'), ('6', 'Laroque-des-Albères'), ('7', 'Montesquieu-des-Albères'), ('8', 'Ortaffa'), ('9', 'Palau-del-Vidre'), ('10', 'Ortaffa'), ('11', 'Port-Vendres'), ('12', 'Port-Vendres'), ('13', 'Saint-André'), ('14', 'Saint-Genis-des-Fontaines'), ('15', 'Sorède'), ('16', 'Villelongue-dels-Monts'), ('17', 'Communauté de Communes'), ('18', 'Département'), ('18', 'Pays')], default='-----', max_length=2, verbose_name='Territoire'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('0', 'Annonce'), ('1', 'Administratif'), ('2', 'Mesure / action'), ('3', 'Echanges avec les candidats'), ('4', 'Réunion'), ('5', 'Idée'), ('6', 'Listes signataires'), ('7', 'Divers'), ('8', 'Suivi')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
