# Generated by Django 2.2.13 on 2020-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200730_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='territoire',
            field=models.CharField(choices=[('', '-----------'), ('0', 'Argelès-sur-Mer,'), ('1', 'Bages'), ('2', 'Banyuls-sur-Mer'), ('3', 'Cerbère'), ('4', 'Collioure'), ('5', 'Elne'), ('6', 'Laroque-des-Albères'), ('7', 'Montesquieu-des-Albères'), ('8', 'Ortaffa'), ('9', 'Palau-del-Vidre'), ('10', 'Ortaffa'), ('11', 'Port-Vendres'), ('12', 'Saint-André'), ('13', 'Saint-Genis-des-Fontaines'), ('14', 'Sorède'), ('15', 'Villelongue-dels-Monts'), ('16', 'Communauté de Communes'), ('17', 'Département'), ('18', 'Pays')], default='-----', max_length=2, verbose_name='Territoire'),
        ),
    ]
