# Generated by Django 2.2.13 on 2020-07-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200730_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='territoire',
            field=models.CharField(choices=[('0', '-----------'), ('1', 'Communauté de Communes'), ('2', 'Département'), ('3', 'Pays'), ('4', 'Argelès-sur-Mer,'), ('5', 'Bages'), ('6', 'Banyuls-sur-Mer'), ('7', 'Cerbère'), ('8', 'Collioure'), ('9', 'Elne'), ('10', 'Laroque-des-Albères'), ('11', 'Montesquieu-des-Albères'), ('12', 'Ortaffa'), ('13', 'Palau-del-Vidre'), ('14', 'Ortaffa'), ('15', 'Port-Vendres'), ('16', 'Saint-André'), ('17', 'Saint-Genis-des-Fontaines'), ('18', 'Sorède'), ('19', 'Villelongue-dels-Monts')], default='-----', max_length=2, verbose_name='Territoire'),
        ),
    ]
