# Generated by Django 2.2.13 on 2020-08-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200730_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('0', 'Annonce'), ('1', 'Administratif'), ('2', 'Mesure / action'), ('3', 'Echanges avec les candidats'), ('4', 'Réunion du collectif'), ('5', 'Idées'), ('6', 'Listes signataires'), ('7', 'Divers'), ('8', 'Suivi'), ('9', 'Conseils municipaux')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
